version: '3.8'

services:
  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx_service
    build: ./srcs/requirements/nginx
    ports:
      - "${NGINX_PORT}:443"  # Use environment variable for Nginx port
    volumes:
      - ./srcs/requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./srcs/requirements/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - wordpress
    networks:
      - inception

  # MariaDB service
  mariadb:
    image: mariadb:latest
    container_name: mariadb_service
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}  # Load password from .env
      MYSQL_DATABASE: ${MYSQL_DATABASE}  # Load database name from .env
      MYSQL_USER: ${MYSQL_USER}  # Load database user from .env
      MYSQL_PASSWORD: ${MYSQL_PWD}  # Load user password from .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

  # WordPress service
  wordpress:
    image: wordpress:latest
    container_name: wordpress_service
    environment:
      WORDPRESS_DB_HOST: mariadb:3306  # Hardcoded because it's an internal service link
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}  # Load from .env
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}  # Load from .env
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PWD}  # Load from .env
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception

# Networks
networks:
  inception:
    driver: bridge

# Volumes
volumes:
  db_data:
  wp_data:

# Path to your environment file
env_file:
  - ./srcs/.env  