
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nnabaeei <nnabaeei@student.42heilbronn.    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/12 10:15:37 by nnabaeei          #+#    #+#              #
#    Updated: 2024/10/13 11:27:48 by nnabaeei         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# version: "3.8"
# Path to your environment file
# env_file: ./srcs/.env  

services:
  nginx:
    container_name: nginx_service
    build: 
      context: ./requirements/nginx/
      args:
        - VAR=${NGINX_PORT}
    ports:
      - "${NGINX_PORT:?error}:$NGINX_PORT"  # Use environment variable for Nginx port
    volumes:
      - wp_data:/var/www/html
      - ./requirements/nginx/conf/nginx.conf.template:/etc/nginx/nginx.conf.template # create this template to be used by envsubst in the nignx docker container
      - ./requirements/nginx/tools/nginx-entrypoint.sh:/usr/local/bin/nginx-entrypoint.sh
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - wordpress
    networks:
      - inception

  # MariaDB service
  mariadb:
    container_name: mariadb_service
    build: ./requirements/mariadb/
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    ports:
      - "3306:3306"

  #WordPress service
  wordpress:
    container_name: wordpress_service
    build: ./requirements/wordpress/
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    restart: always

# Networks
networks:
  inception:
    driver: bridge

# Volumes
volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/db_data
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wp_data